# Generated by Django 3.1.1 on 2020-10-03 06:12

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='exchange-2')),
        ),
    ]
