# Generated by Django 3.1 on 2020-09-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200917_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quantitiy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='exp_date',
            field=models.DateField(default='2020-10-19'),
        ),
    ]
