# Generated by Django 3.1.1 on 2020-09-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200919_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='exp_date',
            field=models.DateField(default='2020-10-20'),
        ),
    ]
