# Generated by Django 3.1 on 2020-09-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200922_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='quantitiy',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='post',
            name='exp_date',
            field=models.DateField(default='2020-10-23'),
        ),
    ]
