# Generated by Django 3.1.1 on 2020-09-24 17:05

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200923_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='exchange-2'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='exp_date',
            field=models.DateField(default='2020-10-24'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
