# Generated by Django 3.1 on 2020-09-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20200924_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='posts',
            field=models.ManyToManyField(to='main_app.Post'),
        ),
    ]
