# Generated by Django 3.1 on 2020-09-29 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20200926_1739'),
        ('main_app', '0015_auto_20200926_2059'),
    ]

    operations = [
    ]
