# Generated by Django 3.1 on 2020-09-30 00:58

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_merge_20200929_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='exp_date',
            field=models.DateField(default='2020-10-30'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=1, upload_to=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='exchange-2')),
            preserve_default=False,
        ),
    ]
